#!/bin/sh
### BEGIN INIT INFO
# Provides:             service1
# Required-Start:       
# Required-Stop:        
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Service 1 
### END INIT INFO

# Le chemin vers votre binaire service1
SERVICE1_BIN="/usr/bin/service1"

do_start()
{
    $SERVICE1_BIN &
}

do_stop()
{
    pkill -f "$SERVICE1_BIN"
}

case "$1" in
  start) do_start ;;
  stop)  do_stop  ;;
  restart) do_stop; do_start ;;
  *) echo "Usage: $0 {start|stop|restart}" >&2; exit 1 ;; 
esac

exit 0
